package com.stv.launcher.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APP_BADGE.
 */
public class AppBadge {

    private Long id;
    private String packageName;
    private String className;
    private String msgType;
    private String msgCount;

    public AppBadge() {
    }

    public AppBadge(Long id) {
        this.id = id;
    }

    public AppBadge(Long id, String packageName, String className, String msgType, String msgCount) {
        this.id = id;
        this.packageName = packageName;
        this.className = className;
        this.msgType = msgType;
        this.msgCount = msgCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getMsgType() {
        return msgType;
    }

    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    public String getMsgCount() {
        return msgCount;
    }

    public void setMsgCount(String msgCount) {
        this.msgCount = msgCount;
    }

}
