package com.stv.launcher.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.stv.launcher.db.AppBadge;
import com.stv.launcher.db.ShortcutInfo;

import com.stv.launcher.db.AppBadgeDao;
import com.stv.launcher.db.ShortcutInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appBadgeDaoConfig;
    private final DaoConfig shortcutInfoDaoConfig;

    private final AppBadgeDao appBadgeDao;
    private final ShortcutInfoDao shortcutInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appBadgeDaoConfig = daoConfigMap.get(AppBadgeDao.class).clone();
        appBadgeDaoConfig.initIdentityScope(type);

        shortcutInfoDaoConfig = daoConfigMap.get(ShortcutInfoDao.class).clone();
        shortcutInfoDaoConfig.initIdentityScope(type);

        appBadgeDao = new AppBadgeDao(appBadgeDaoConfig, this);
        shortcutInfoDao = new ShortcutInfoDao(shortcutInfoDaoConfig, this);

        registerDao(AppBadge.class, appBadgeDao);
        registerDao(ShortcutInfo.class, shortcutInfoDao);
    }
    
    public void clear() {
        appBadgeDaoConfig.getIdentityScope().clear();
        shortcutInfoDaoConfig.getIdentityScope().clear();
    }

    public AppBadgeDao getAppBadgeDao() {
        return appBadgeDao;
    }

    public ShortcutInfoDao getShortcutInfoDao() {
        return shortcutInfoDao;
    }

}
