package com.stv.launcher.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHORTCUT_INFO.
 */
public class ShortcutInfo {

    private Long id;
    private Integer index;
    private Integer type;
    private Integer spanX;
    private Integer spanY;
    private Integer row;
    private Integer column;
    private Integer width;
    private Integer height;
    private String title;
    private String description;
    private String packageName;
    private String className;
    private Integer flags;
    private Long container;
    private String containerName;
    private Long installTime;
    private String componentNameStr;
    private String iconUrl;
    private Integer backgroundResID;
    private Integer inFolderIndex;
    private String reserve1;
    private String reserve2;
    private String reserve3;

    public ShortcutInfo() {
    }

    public ShortcutInfo(Long id) {
        this.id = id;
    }

    public ShortcutInfo(Long id, Integer index, Integer type, Integer spanX, Integer spanY, Integer row, Integer column, Integer width, Integer height, String title, String description, String packageName, String className, Integer flags, Long container, String containerName, Long installTime, String componentNameStr, String iconUrl, Integer backgroundResID, Integer inFolderIndex, String reserve1, String reserve2, String reserve3) {
        this.id = id;
        this.index = index;
        this.type = type;
        this.spanX = spanX;
        this.spanY = spanY;
        this.row = row;
        this.column = column;
        this.width = width;
        this.height = height;
        this.title = title;
        this.description = description;
        this.packageName = packageName;
        this.className = className;
        this.flags = flags;
        this.container = container;
        this.containerName = containerName;
        this.installTime = installTime;
        this.componentNameStr = componentNameStr;
        this.iconUrl = iconUrl;
        this.backgroundResID = backgroundResID;
        this.inFolderIndex = inFolderIndex;
        this.reserve1 = reserve1;
        this.reserve2 = reserve2;
        this.reserve3 = reserve3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSpanX() {
        return spanX;
    }

    public void setSpanX(Integer spanX) {
        this.spanX = spanX;
    }

    public Integer getSpanY() {
        return spanY;
    }

    public void setSpanY(Integer spanY) {
        this.spanY = spanY;
    }

    public Integer getRow() {
        return row;
    }

    public void setRow(Integer row) {
        this.row = row;
    }

    public Integer getColumn() {
        return column;
    }

    public void setColumn(Integer column) {
        this.column = column;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getFlags() {
        return flags;
    }

    public void setFlags(Integer flags) {
        this.flags = flags;
    }

    public Long getContainer() {
        return container;
    }

    public void setContainer(Long container) {
        this.container = container;
    }

    public String getContainerName() {
        return containerName;
    }

    public void setContainerName(String containerName) {
        this.containerName = containerName;
    }

    public Long getInstallTime() {
        return installTime;
    }

    public void setInstallTime(Long installTime) {
        this.installTime = installTime;
    }

    public String getComponentNameStr() {
        return componentNameStr;
    }

    public void setComponentNameStr(String componentNameStr) {
        this.componentNameStr = componentNameStr;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public Integer getBackgroundResID() {
        return backgroundResID;
    }

    public void setBackgroundResID(Integer backgroundResID) {
        this.backgroundResID = backgroundResID;
    }

    public Integer getInFolderIndex() {
        return inFolderIndex;
    }

    public void setInFolderIndex(Integer inFolderIndex) {
        this.inFolderIndex = inFolderIndex;
    }

    public String getReserve1() {
        return reserve1;
    }

    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    public String getReserve2() {
        return reserve2;
    }

    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    public String getReserve3() {
        return reserve3;
    }

    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3;
    }

}
